// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using RagChatbot.DataAccess.Data;

#nullable disable

namespace RagChatbot.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605044836_AddContactMessageTable")]
    partial class AddContactMessageTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyQueryCount")
                        .HasColumnType("integer");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastQueryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Subscription")
                        .HasColumnType("integer");

                    b.Property<int>("TodayChatCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyQueryCount = 0,
                            Email = "admin@gmail.com",
                            FirstName = "Quản trị",
                            IsActive = true,
                            LastActiveDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Hệ thống",
                            LastQueryDate = new DateTime(2026, 6, 5, 4, 48, 36, 158, DateTimeKind.Utc).AddTicks(9241),
                            PasswordHash = "Y07d+n5+EQi6ce7n2ti3NIbfnCs1+TT9LE/LNjozxlc=",
                            Role = "Admin",
                            Subscription = 0,
                            TodayChatCount = 0
                        },
                        new
                        {
                            Id = 2,
                            DailyQueryCount = 0,
                            DepartmentId = 1,
                            Email = "lecturer@gmail.com",
                            FirstName = "Nguyễn",
                            IsActive = true,
                            LastActiveDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Giảng Viên 1",
                            LastQueryDate = new DateTime(2026, 6, 5, 4, 48, 36, 158, DateTimeKind.Utc).AddTicks(9590),
                            PasswordHash = "Yz9PJlOwHiN+8KJrW6mbQYyJTl9BLR121umofM8/fNg=",
                            Role = "Lecturer",
                            Subscription = 0,
                            TodayChatCount = 0
                        },
                        new
                        {
                            Id = 3,
                            DailyQueryCount = 0,
                            Email = "student1@gmail.com",
                            FirstName = "Học",
                            IsActive = true,
                            LastActiveDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Sinh 1",
                            LastQueryDate = new DateTime(2026, 6, 5, 4, 48, 36, 158, DateTimeKind.Utc).AddTicks(9608),
                            PasswordHash = "q5AEtNl18HLfc3SmE3xdUM9B4HfRQy9LxxhIBjdDrhk=",
                            Role = "Student",
                            Subscription = 0,
                            TodayChatCount = 0
                        },
                        new
                        {
                            Id = 4,
                            DailyQueryCount = 0,
                            Email = "student2@gmail.com",
                            FirstName = "Học",
                            IsActive = true,
                            LastActiveDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Sinh 2",
                            LastQueryDate = new DateTime(2026, 6, 5, 4, 48, 36, 158, DateTimeKind.Utc).AddTicks(9622),
                            PasswordHash = "++RMfEkC1qU39CHjzrIMeIRvyI14mE55Nv/47HrPF1I=",
                            Role = "Student",
                            Subscription = 0,
                            TodayChatCount = 0
                        },
                        new
                        {
                            Id = 100,
                            DailyQueryCount = 0,
                            DepartmentId = 1,
                            Email = "hod@gmail.com",
                            FirstName = "Trưởng",
                            IsActive = true,
                            LastActiveDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastName = "Khoa CNTT",
                            LastQueryDate = new DateTime(2026, 6, 5, 4, 48, 36, 158, DateTimeKind.Utc).AddTicks(9632),
                            PasswordHash = "Cl7afaR0DnYdIJfugd6f3iJedk+4iQxVU2eK8vcBa6w=",
                            Role = "HeadOfDepartment",
                            Subscription = 0,
                            TodayChatCount = 0
                        });
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetObjectId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Citations")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatSessions");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RelatedId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 5, 4, 48, 36, 158, DateTimeKind.Utc).AddTicks(8939),
                            Description = "Khoa CNTT",
                            Name = "Công nghệ Thông tin"
                        });
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UploaderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("UploaderId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.DocumentChunk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<int?>("PageNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.HasIndex("Code", "UserId")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.SubjectAssignment", b =>
                {
                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("LecturerId")
                        .HasColumnType("integer");

                    b.HasKey("SubjectId", "LecturerId");

                    b.HasIndex("LecturerId");

                    b.ToTable("SubjectAssignments");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.AppUser", b =>
                {
                    b.HasOne("RagChatbot.DataAccess.EntityModels.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.AuditLog", b =>
                {
                    b.HasOne("RagChatbot.DataAccess.EntityModels.AppUser", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.ChatMessage", b =>
                {
                    b.HasOne("RagChatbot.DataAccess.EntityModels.ChatSession", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.ChatSession", b =>
                {
                    b.HasOne("RagChatbot.DataAccess.EntityModels.Subject", "Subject")
                        .WithMany("ChatSessions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbot.DataAccess.EntityModels.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.Document", b =>
                {
                    b.HasOne("RagChatbot.DataAccess.EntityModels.Subject", "Subject")
                        .WithMany("Documents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbot.DataAccess.EntityModels.AppUser", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.DocumentChunk", b =>
                {
                    b.HasOne("RagChatbot.DataAccess.EntityModels.Document", "Document")
                        .WithMany("DocumentChunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.Subject", b =>
                {
                    b.HasOne("RagChatbot.DataAccess.EntityModels.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RagChatbot.DataAccess.EntityModels.AppUser", "User")
                        .WithMany("Subjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.SubjectAssignment", b =>
                {
                    b.HasOne("RagChatbot.DataAccess.EntityModels.AppUser", "Lecturer")
                        .WithMany("SubjectAssignments")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RagChatbot.DataAccess.EntityModels.Subject", "Subject")
                        .WithMany("Assignments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.AppUser", b =>
                {
                    b.Navigation("SubjectAssignments");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.Department", b =>
                {
                    b.Navigation("Subjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.Document", b =>
                {
                    b.Navigation("DocumentChunks");
                });

            modelBuilder.Entity("RagChatbot.DataAccess.EntityModels.Subject", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ChatSessions");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
